services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.docker
    container_name: vue-admin-dashboard
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
